name: parallel-jobs-example

on: 
  push:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing work"
  job-b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing another work at same time"