name: actions-example

on:
  push:
    
jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '18.16.1'

      - 
        name: Install repo deps
        run: npm install

      - name: Run script from repo
        run: node helloWorld.js
