name: event-triggers-example

on:
  push:
    branches:
      - 'master'
      # - 'foo/*'
      # - 'foo/**'
      # - '!foo/*/456'
    tags:
      - '*'
  pull_request:
    branches:
      - 'develop'
  schedule:
    - cron: '*/15 * * * *'

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Event
        run: echo "Triggered event"
      - name: Say Hello
        run: echo "Hello world!"
